// 全局的mutations-type类型
export const SAVE_LOADING_STATE = 'SAVE_LOADING_STATE';

export const SAVE_USER_INFO = 'SAVE_USER_INFO';

export const SAVE_LOGIN_INFO = 'SAVE_LOGIN_INFO';

export const SAVE_BUTTON_CONFIG = 'SAVE_BUTTON_CONFIG';

export const SAVE_PERMIT_PATH_INFO = 'SAVE_PERMIT_PATH_INFO';

export const SAVE_PERMIT_RESOURCE_INFO = 'SAVE_PERMIT_RESOURCE_INFO';

export const SAVE_QUERY_PARAMS_INFO = 'SAVE_QUERY_PARAMS_INFO';

export const SAVE_PAGE_CACHE_STATUS = 'SAVE_PAGE_CACHE_STATUS';

// 保存多页签对象
export const SAVE_MULTIPLE_OBJ = 'SAVE_MULTIPLE_OBJ';

// 导航激活index
export const SAVE_NAV_INDEX = 'SAVE_NAV_INDEX';

// 展开指定导航面板INDEX
export const SAVE_NAV_SINGLE_INDEX = 'SAVE_NAV_SINGLE_INDEX';

// 多页签
export const SAVE_TAB_LABELS = 'SAVE_TAB_LABELS';

// 草稿箱
export const SAVE_DRAFT_BOX_OBJ = 'SAVE_DRAFT_BOX_OBJ';

// 发件箱
export const SAVE_OUT_BOX_OBJ = 'SAVE_OUT_BOX_OBJ';

// 收件箱
export const SAVE_IN_BOX_OBJ = 'SAVE_IN_BOX_OBJ';

// 回收站
export const SAVE_RECYCLE_BIN_OBJ = 'SAVE_RECYCLE_BIN_OBJ';

// 消息中心
export const SAVE_MESSAGE_CENTER_OBJ = 'SAVE_MESSAGE_CENTER_OBJ';

// 纠纷中心
export const SAVE_DISPUTE_CENTER_OBJ = 'SAVE_DISPUTE_CENTER_OBJ';

//订单管理
// export const SAVE_ORDER_LIST_MANAGEMENT = 'SAVE_ORDER_LIST_MANAGEMENT';

//订单信息
export const SAVE_ORDER_INFORMATION = 'SAVE_ORDER_INFORMATION';

//邮箱管理
export const SAVE_MAIL_MANAGEMENT = 'SAVE_MAIL_MANAGEMENT';

//任务权限管理
export const SAVE_JURISDICTION_MANAGEMENT = 'SAVE_JURISDICTION_MANAGEMENT';

//系统配置
/* 标签配置 */
export const SAVE_LABEL_CONFIGURATION_LIST_INFO = 'SAVE_LABEL_CONFIGURATION_LIST_INFO';
/* 邮件分类配置 */
export const SAVE_EMAIL_CLASS_CONFIGURATION_LIST_INFO = 'SAVE_EMAIL_CLASS_CONFIGURATION_LIST_INFO';
/* 自动发信规则 */
export const SAVE_AUTOMATION_SEND_RULE_LIST_INFO = 'SAVE_AUTOMATION_SEND_RULE_LIST_INFO';
/* 自动回复规则 */
export const SAVE_AUTOMATION_REPLY_RULE_LIST_INFO = 'SAVE_AUTOMATION_REPLY_RULE_LIST_INFO';
/* 自动售后单规则 */
export const SAVE_AUTOMATION_AFTER_SALE_RULE_LIST_INFO = 'SAVE_AUTOMATION_AFTER_SALE_RULE_LIST_INFO';
/* 自动信息记录 */
export const SAVE_AUTOMATION_MESSAGE_LIST_INFO = 'SAVE_AUTOMATION_MESSAGE_LIST_INFO';
// 客户评价review
export const SAVE_CUSTOMER_REVIEW_INFO = 'SAVE_CUSTOMER_REVIEW_INFO';
// 客户评价feedback
export const SAVE_CUSTOMER_FEEDBACK_INFO = 'SAVE_CUSTOMER_FEEDBACK_INFO';
// 售后单管理
export const SAVE_AFTER_SALE_INFO = 'SAVE_AFTER_SALE_INFO';
// 客诉列表
export const SAVE_CUSTOMER_COMPLAINT_INFO = 'SAVE_CUSTOMER_COMPLAINT_INFO';
// 收款请求列表
export const SAVE_RECEIPT_REQUEST_INFO = 'SAVE_RECEIPT_REQUEST_INFO';
// 登记收款列表
export const SAVE_REGISTERED_PAYMENT_INFO = 'SAVE_REGISTERED_PAYMENT_INFO';
// 系统配置 基础数据配置
export const SAVE_BASIC_DATA_INFO = 'SAVE_BASIC_DATA_INFO';
// 系统配置 发票信息配置
export const SAVE_INVOICE_CONFIGURATION_INFO = 'SAVE_INVOICE_CONFIGURATION_INFO';
// 系统配置 模板配置
export const SAVE_TEMPLATE_CONFIG_INFO = 'SAVE_TEMPLATE_CONFIG_INFO';
// 系统配置 模板分类配置
export const SAVE_TEMPLATE_CLASS_INFO = 'SAVE_TEMPLATE_CLASS_INFO';

// 公共搜索配置
export const SAVE_COMMON_SEARCH_CONFIG = 'SAVE_COMMON_SEARCH_CONFIG';

// 勾选搜索条件
export const SAVE_CHECK_SEARCH_INFO = 'SAVE_CHECK_SEARCH_INFO';

// 勾选搜索条件
export const SAVE_CHECK_MAINDATA = 'SAVE_CHECK_MAINDATA';

